<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Emerald Heart Lighthouse Collection - About Us</title>

    <!--Included Third Party Library and Javascript and CSS-->
    <!--<script type="text/javascript" src="js/angular.min.js"></script>-->
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <link rel="stylesheet" href="../css/bootstrap-responsive.min.css">

    <!-- Included Application specific CSS and Javascript -->
    <link rel="stylesheet" href="../css/reset.css">
    <link rel="stylesheet" href="../css/main.css">

</head>

<body>

    <header>

        <h1><a href="../index.html"><img src="../css/images/contentimages/logo.png"></a></h1>

        <form>

            <ul>
                <li><a href="account_email_information.inc">Email Sign-up</a></li>
                <li> <a href="">Customer Care</a></li>
            </ul>
            <p><input id="search" type="text" /></p><p class="input">Search</p>

        </form>

        <!-- ------------------------------------ MAIN NAVIGATION START ---------------------------------------------->
        <nav id='nav'>
            <ul>

                <li class='active'><a href='whats_new.inc'><span>What's New</span></a></li>
                <li class='active has-sub'><a href='current_products.inc'><span>Current Products</span></a>
                    <ul>
                        <li><a href='#'><span>Home Decor</span></a></li>
                        <li class='last'><a href='#'><span>Books</span></a></li>
                    </ul>
                </li>

                <li class='active'><a href='about_us.inc'><span>About Us</span></a></li>
                <li class="active"><a href="about_us.inc"><span>Contact Us</span></a> </li>
                <li class='active last'><a href='customer_feedback.inc'><span>Customer Feedback</span></a></li>

            </ul>
        </nav>
        <!-- ------------------------------------ MAIN NAVIGATION END ------------------------------------------------>

        <!-- WELCOME MESSAGE AND SHOPPING CART INFORMATION ----------------->
        <p>Welcome!
            <!--<a href="account_email_information.html"> Sign In</a> or <a href="account_email_information.html"> Create a Account</a> -->
        </p>

    </header>

    <section>

        <div id="about_us_content">
            <h1>About Us</h1>
            <p>Emerald Heart Light House Collection is dedicated to help both men and
                women find that unique gift for that someone special, whether they are a
                family member, a friend or just want to buy something for someone that they
                are thinking about that will be cherished for a lifetime.</p>
            <br>
            <p> With the limitless array of unique one of a kind gifts, we are sure to help you
                spark that inner imagination of the soul and touch the depths of not only your
                heart but that of others as well.</p>
            <br>
            <p> The single purpose of the Emerald Heart Lighthouse Collection’s brand,
                craftsmanship and unique services or specialties is to showcase the homemade
                gifts that are unique with no repeats of any kind while providing you that one
                of a kind item that is not purchasable anywhere else.</p>
            <br>
            <p> All of the items within the Emerald Heart Lighthouse Collection website are
                handmade with no two items ever being the same and therefore providing you
                that unique quality stature.  As a purchaser you will walk away knowing that
                you are receiving an item that is uniquely your own.</p>
            <br>
            <p> We hope that you find shopping on our site to be calming, relaxed and user
                friendly.</p>
            <br>
            <p> If you wish to provide us feedback please fill out the customer feedback form,
                send us an email or give us a call us at 1-800-XXX-XXXX, we would love to hear
                from you. </p>

        </div>

        <div id="side_nav">
            <h2>Themes</h2>
                <ul>
                    <li><a href=""> Nautical</a></li>
                    <li><a href=""> Fantasy</a> </li>
                    <li><a href=""> Whimsical</a> </li>
                    <li><a href=""> Nature</a> </li>
                    <li><a href=""> 5 Elements</a> </li>
                    <li><a href=""> Spiritual</a> </li>
                </ul>
            <br>
            <h2>Current Products</h2>
                <ul>
                    <li><a href=""> Home Decor</a> </li>
                    <li><a href=""> Books</a> </li>
                </ul>
        </div>



    </section>

    <section id="bottom_nav">
        <div id="subfooter">
            <ul>
                <li><a href="whats_new.inc">What's New</a> </li>
                <li><a href="customer_feedback.inc">Customer Feedback</a> </li>
                <li><a href="current_products.inc">Current Products</a> </li>
                <li><a href="themes.inc">Themes</a> </li>
                <li><a href="about_us.inc">About Us</a> </li>
                <li><a href="site_map.inc">Site Map</a> </li>
                <li>Customer Service: 1-800-123-4567 </li>
                <li>Orders: 1-800-456-7890</li>
                <li>Email:<a href="mailto:emeraldheartlc@gmail.com"> EmeraldHeartLC@gmail.com</a> </li>
            </ul>
        </div>
    </section>

    <footer>

        <p>All Rights | Copyright April 2014 | Website Maintained by <a href="mailto:whymsicaldesigns@gmail.com">Whymsical Designs</a></p>

    </footer>

</body>
</html>