<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Emerald Heart Lighthouse Collection - About Us</title>

    <!--Included Third Party Library and Javascript and CSS-->
    <!--<script type="text/javascript" src="js/angular.min.js"></script>-->
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <link rel="stylesheet" href="../css/bootstrap-responsive.min.css">

    <!-- Included Application specific CSS and Javascript -->
    <link rel="stylesheet" href="../css/reset.css">
    <link rel="stylesheet" href="../css/main.css">

</head>

<body>

<header>

    <h1><a href="../main.inc"><img src="../css/images/contentimages/logo.png"></a></h1>

    <form>

        <ul>
            <li><a href="email_signup_page.inc">Email Sign-up</a></li>
            <li> <a href="contact.inc">Customer Care</a></li>
        </ul>
        <p><input id="search" type="text" /></p><p class="input">Search</p>

    </form>

    <!-- ------------------------------------ MAIN NAVIGATION START ---------------------------------------------->
    <nav id='nav'>
        <ul>

            <li class='active'><a href='whats_new.inc'><span>What's New</span></a></li>
            <li class='active has-sub'><a href='current_products.inc'><span>Current Products</span></a>
                <ul>
                    <li><a href='#'><span>Home Decor</span></a></li>
                    <li class='last'><a href='#'><span>Books</span></a></li>
                </ul>
            </li>

            <li class='active'><a href='about_us.inc'><span>About Us</span></a></li>
            <li class="active"><a href="contact.inc"><span>Contact Information</span></a> </li>
            <li class='active last'><a href='customer_feedback.inc'><span>Customer Feedback</span></a></li>

        </ul>
    </nav>
    <!-- ------------------------------------ MAIN NAVIGATION END ------------------------------------------------>

    <!-- WELCOME MESSAGE AND SHOPPING CART INFORMATION ----------------->
    <p>Welcome!
        <!--<a href="account_email_information.html"> Sign In</a> or <a href="account_email_information.html"> Create a Account</a> -->
    </p>

</header>

<section>

    <div id="contact">
        <h1>We would love to hear from you!</h1>

        <p>If you have a question regarding any of our products please do not hesitate to send us a note.
        We will be glad to answer any questions that you might have regarding any one of our products.  We
        can be reached via E-mail, Phone, or Address.</p>
        <p>Live Chat with a representative is coming soon!</p>



        <form>

            <ul>
                <li>E-mail: <a href="mailto:emeraldheartlc@gmail.com"> E-mail Us</a></li>
                <li>Phone:<p>1-800-XXX-XXXX</p></li>
                <li>Address:
                    <p>Emerald Heart Lighthouse Collect</p>
                    <p>c/o Customer Service</p>
                    <p>PO Box 12358</p>
                    <p>Arkport, N.Y 14807</p>
            </ul>

        </form>


    </div>

    <div id="side_nav">
        <h2>Themes</h2>
        <ul>
            <li><a href=""> Nautical</a></li>
            <li><a href=""> Fantasy</a> </li>
            <li><a href=""> Whimsical</a> </li>
            <li><a href=""> Nature</a> </li>
            <li><a href=""> 5 Elements</a> </li>
            <li><a href=""> Spiritual</a> </li>
        </ul>
        <br>
        <h2>Current Products</h2>
        <ul>
            <li><a href=""> Home Decor</a> </li>
            <li><a href=""> Books</a> </li>
        </ul>
    </div>



</section>

<section id="bottom_nav">
    <div id="subfooter">
        <ul>
            <li><a href="whats_new.inc">What's New</a> </li>
            <li><a href="customer_feedback.inc">Customer Feedback</a> </li>
            <li><a href="current_products.inc">Current Products</a> </li>
            <li><a href="themes.inc">Themes</a> </li>
            <li><a href="about_us.inc">About Us</a> </li>
            <li><a href="site_map.inc">Site Map</a> </li>
            <li>Customer Service: 1-800-123-4567 </li>
            <li>Orders: 1-800-456-7890</li>
            <li>Email:<a href="mailto:emeraldheartlc@gmail.com"> EmeraldHeartLC@gmail.com</a> </li>
        </ul>
    </div>
</section>

<footer>
    <p>All Rights</p>
    <p>&copy; April 2014</p>
    <p>Website Maintained by <a href="mailto:whymsicaldesigns@gmail.com">Whymsical Designs</a></p>
</footer>

</body>
</html>