<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Emerald Heart Lighthouse Collection</title>

     <!--Included Third Party Library and Javascript and CSS-->
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <link rel="stylesheet" href="../css/bootstrap-responsive.min.css">

    <!-- Included Application specific CSS and Javascript -->
    <link href="../js/themes/1/js-image-slider.css" rel="stylesheet" type="text/css" />
    <script src="../js/themes/1/js-image-slider.js" type="text/javascript"></script>
    <link rel="stylesheet" href="../css/reset.css">
    <link rel="stylesheet" href="../css/main.css">

</head>

<body>
    <header>

            <h1><a href="main.inc"><img src="../css/images/contentimages/logo.png"></a></h1>

            <form>

                <ul>
                    <li><a href="account_email_information.inc">Email Sign-up</a></li>
                    <li> <a href="contact.inc">Customer Care</a></li>
                </ul>
                <p><input id="search" type="text" /></p><p class="input">Search</p>

            </form>

<!-- ------------------------------------ MAIN NAVIGATION START ---------------------------------------------->
        <nav id='nav'>
            <ul>

                <li class='active'><a href='whats_new.inc'><span>What's New</span></a></li>
                <li class='active has-sub'><a href='current_products.inc'><span>Current Products</span></a>
                    <ul>
                        <li><a href='#'><span>Home Decor</span></a></li>
                        <li class='last'><a href='#'><span>Books</span></a></li>
                    </ul>
                </li>

                <li class='active'><a href='about_us.inc'><span>About Us</span></a></li>
                <li class="active"><a href="contact.inc"><span>Contact Information</span></a> </li>
                <li class='active last'><a href='customer_feedback.inc'><span>Customer Feedback</span></a></li>

            </ul>
        </nav>
<!-- ------------------------------------ MAIN NAVIGATION END ------------------------------------------------>

        <!-- WELCOME MESSAGE AND SHOPPING CART INFORMATION ----------------->
        <p>Welcome!
            <!--<a href="account_email_information.inc"> Sign In</a> or <a href="account_email_information.inc"> Create a Account</a> -->
        </p>

    </header>
<!-- --------------------------------- CENTER CONTENT AREA ------------------------------------------ -->
    <section>
        <blockquote>"It's All About The Heart and Soul"<p>~Sue Frazier</p></blockquote>

        <div id="product_images">
            <div id="sliderFrame">
                <div id="slider">
                    <a href=""> <img src="../css/images/image_slider/unicorn.jpg" alt="Mystical Carousel Unicorn" /></a>
                    <a href=""> <img src="../css/images/image_slider/starclown.jpg" alt="Clown"/></a>
                    <a href=""> <img src="../css/images/image_slider/holidaywreath.jpg" alt="Holiday Wreath"/></a>
                    <a href=""> <img src="../css/images/image_slider/seashellwreath.jpg" alt="Sea Shell Wreath"/></a>
                    <a href=""> <img src="../css/images/product-images/underwaterdream.jpg" alt="Underwater Dream" /></a>
                </div>
            </div>
        </div>

        <div id="content">

            <p>Find that one of a kind gift for that someone special!</p>
            <br>
            <p>Discover the array of original, and unique gifts that are sure to spark the imagination of
                the soul and touch the depths of the Heart!</p>

        </div>

    </section>

    <section id="bottom_nav">
        <div id="subfooter">
            <ul>
                <li><a href="whats_new.inc">What's New</a> </li>
                <li><a href="customer_feedback.inc">Customer Feedback</a> </li>
                <li><a href="current_products.inc">Current Products</a> </li>
                <li><a href="themes.inc">Themes</a> </li>
                <li><a href="about_us.inc">About Us</a> </li>
                <li><a href="site_map.inc">Site Map</a> </li>
                <li>Customer Service: 1-800-123-4567 </li>
                <li>Orders: 1-800-456-7890</li>
                <li>Email:<a href="mailto:emeraldheartlc@gmail.com"> EmeraldHeartLC@gmail.com</a> </li>
            </ul>
        </div>
    </section>

    <footer>
        <p>All Rights | Copyright April 2014 | Website Maintained by <a href="mailto:whymsicaldesigns@gmail.com">Whymsical Designs</a></p>
    </footer>
</body>
</html>